### ISSUE TITLE
Errors when performing BiocCheck

### ISSUE THREAD

**Issue by wleoncio** [SystemsBiologist/CellMigRation#15]
Running BiocCheck on the latest commit (e871428e9e5dd71cb8d3ea729db5c71bbfccac00) yields the following errors:

```
[1] "No biocViews terms found."                                                                                      
[2] "No 'vignettes' directory."                                                                                      
[3] "At least 80% of man pages documenting exported objects must have runnable examples. The following pages do not:"
[4] "Maintainer must register at the support site; visit https://support.bioconductor.org/accounts/signup/ ."  
```

To address each of those issues, the following must be done:
1. ~Add the "biocViews: " field to the DESCRIPTION file, containing some relevant keywords from [this list](https://www.bioconductor.org/packages/release/BiocViews.html). [Here](https://github.com/ocbe-uio/DIscBIO/blob/master/DESCRIPTION) is an example of how it could look like~
2. Create a Vignette and put its source code (e.g. an Rmarkdown file) in a "vignettes" directory
3. Create examples for more functions (or internalize more functions by removing the `@export` Roxygen tag)
4. ~The package maintainer (@SystemsBiologist) must sign up to the Bioconductor support site. Registration link [here](https://support.bioconductor.org/accounts/signup/)~

**Comment by SystemsBiologist** [comment]
I added the "biocViews: " and signed up to the Bioconductor support site. I think all the functions in my part have examples!
Soon we will add the final vignettes.

**Comment by wleoncio** [comment]
> I added the "biocViews

Thanks for this! Unfortunately, the entered tags are not valid. All biocViews must be drawn from the list on the link below:

https://www.bioconductor.org/packages/release/BiocViews.html

New tags are unfortunately not accepted and issue a warning on BiocCheck. See below:
![image](https://user-images.githubusercontent.com/8234768/87011095-c1a9ba00-c1c7-11ea-9fb2-b48c7d4d60ce.png)

Please fix and recommit.

**Comment by SystemsBiologist** [comment]
Hi Waldir, I added it again. I hope it is OK now!

**Comment by wleoncio** [comment]
Yes, @SystemsBiologist, that one's solved. Thanks for the quick action! I've crossed the addressed points on the original post.

@dami82, is it possible to add examples to at least some of the functions from the output below (from `BiocCheck::BiocCheck()` on commit e5d772c6e6d2f83314a021c2688f77d3e27afb8a)? We need just enough to cover 80% of the package functions.

> * ERROR: At least 80% of man pages documenting exported objects must have runnable examples. The following
>   pages do not:
>   aggregateTrackedCells.Rd, CellMig-class.Rd, CellMigPCA.Rd, CellTracker.Rd, ComputeTracksStats.Rd,
>   DiAutoCor.Rd, DiRatio.Plot.Rd, FinRes.Rd, getCellsMeta.Rd, getCellsStats.Rd, getImageStacks.Rd,
>   getOptimizedParams.Rd, getPopulationStats.Rd, getTracks.Rd, LoadTiff.Rd, OptimizeParams.Rd, plot3DAllTracks.Rd,
>   setCellsMeta.Rd, VeAutoCor.Rd, visualizeCellTracks.Rd, VisualizeImg.Rd, VisualizeStackCentroids.Rd

**Comment by dami82** [comment]
BiocCheck completes with no errors

Summary:
ERROR count: 0
WARNING count: 0
NOTE count: 9
