### ISSUE TITLE
Usage of "T" and "F" in three functions

### ISSUE THREAD

**Issue by wleoncio** [SystemsBiologist/CellMigRation#16]
# Summary

The following functions contain reference to a `T` object whose meaning I can't understand:

- [rmPreProcessing()](https://github.com/ocbe-uio/CellMigRation/blob/c67ae1697685545b59d9e2c6704e00dfb587250a/R/all_functions.R#L3603)
- [VeAutoCor()](https://github.com/ocbe-uio/CellMigRation/blob/c67ae1697685545b59d9e2c6704e00dfb587250a/R/all_functions.R#L5347)
- [wsaPreProcessing()](https://github.com/ocbe-uio/CellMigRation/blob/c67ae1697685545b59d9e2c6704e00dfb587250a/R/all_functions.R#L3857)

# Details

Click on the function names above to be taken to the line containing the objects in question. Since they are part of an equation, I don't think they stand for "TRUE" because there's no point in dividing or multiplying by "one" (`TRUE == 1` in R). On the other hand, I see no other mentioning of T elsewhere in those functions, so either they are not variables/constants or they are out of scope (e.g. global variables). In any case, this is an issue that should be addressed.

# Motivation to fix

Fixing this is _essential_ for an eventual Bioconductor submission, since BiocCheck doesn't allow "T" and "F" to be used at all, issuing a "Use TRUE/FALSE instead of T/F" warning. Moreover, it is considered good practice to avoid ever using "T" and "F" in R because they cause this kind of confusion. More info [here](https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/logical).

# Expected solution

I would like to understand what T and F stand for in these functions so I can modify the lines without interfering in the results of such functions and get the package to pass BiocCheck.

**Comment by SystemsBiologist** [comment]
Hi, 
T= TimeInterval      
so the "T" in these three functions  (rmPreProcessing(), VeAutoCor() wsaPreProcessing()) should be replaced with "TimeInterval"

        Object[[j]][i,23]=((Object[[j]][i,14]* Object[[j]][i+lag,14])+ (Object[[j]][i,15]* Object[[j]][i+lag,15]))/ ((lag*TimeInterval)^2) 

      ID_split[[j]][i,24]= (sqrt(ID_split[[j]][i+1,11])-sqrt(ID_split[[j]][i,11]))/TimeInterval


Somethimes I have used "T=TRUE   and     F=FALSE"

**Comment by wleoncio** [comment]
Thank you for the explanation, Salim. This solves the issue and now the package passes the with flying colors!
