### ISSUE TITLE
Licence change

### ISSUE THREAD

**Issue by wleoncio** [SystemsBiologist/CellMigRation#19]
According to https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software, the use of a CC license is discouraged for software because "CC licenses do not contain specific terms about the distribution of source code, which is often important to ensuring the free reuse and modifiability of software". Thus, **I am proposing a change in the license term of CellMigRation from CC0 to a more appropriate license such as the GPL (my favorite) or the MIT**. I can make the change myself, but I'd like to hear from all the package authors first.

**Comment by osorensen** [comment]
Thanks for raising this issue. Unless there are compelling reasons not to, I support changing the license.

**Comment by wleoncio** [comment]
@SystemsBiologist, @dami82, any opinion on the matter?

**Comment by SystemsBiologist** [comment]
I think both GPL and the MIT are fine!

**Comment by dami82** [comment]
I often use GPL-2 for my Open source R packages.

Best regards,
Damiano

——
Damiano Fantini
