### ISSUE TITLE
Improve documentation on datasets

### ISSUE THREAD

**Issue by wleoncio** [SystemsBiologist/CellMigRation#33]
Source: https://github.com/Bioconductor/Contributions/issues/1618#issuecomment-696258765
- [ ] REQUIRED: Can you provide any source information for the datasets?

**Comment by wleoncio** [comment]
File to be edited: https://github.com/ocbe-uio/cellmigRation/blob/master/R/all_extra.R

**Comment by wleoncio** [comment]
Hey guys, did you have any time to look at this? This and PR #70 are the only things left before we can resubmit the package. Hope we can make it to the end-of-month duedate.

**Comment by dami82** [comment]
Will work on this (add documentation for the datasets) later tonight.... In the meanwhile, PR #70 is done. I tested, the vignette builds. Can you try building the vignette (PR #70) on your side (since I could not reproduce the issue you had, vignette was building anyway)? Thanks!

**Comment by dami82** [comment]
I added a `@details` section for each of the datasets... I think this provides a reasonable "source info" for the data. Also, I guess we can say that we will add the DOI of Salim's Biorxiv (or paper) as soon as it is out. In the meanwhile, I guess we shall stick with an extended `@details` section. @SystemsBiologist , please can you check if the deatils look OK?

**Comment by SystemsBiologist** [comment]
I agree, everything looks OK! 
Good job

**Comment by dami82** [comment]
1) Added a "details" roxygen2 paragraph in each Manual documenting a Dataset to provide information about data generation, collection, and pre-processing.
2) Rebuild the corresponding Rd files in man/
3) todo, long-term: once a biorxiv or the final paper is out with an assigned DOI, we may want to add the corresponding reference/link in the dataset manuals
