### ISSUE TITLE
Add more unit tests

### ISSUE THREAD

**Issue by wleoncio** [SystemsBiologist/CellMigRation#36]
Source: https://github.com/Bioconductor/Contributions/issues/1618#issuecomment-696258765
- [ ] SUGGESTION: We like to see more than one test being performed, you might
give some thought to adding more tests.

**Comment by wleoncio** [comment]
Current status: waiting for new examples (i.e. issue #35) do be done so they can be adapted into unit tests. Writing tests now may be counterproductive given how the behavior of functions may change before the next submission.

**Comment by wleoncio** [comment]
Starting to work on this. I see there are around 70 functions with examples. I'm afraid adding 70-ish tests might make the package fail to build in the allotted time, so maybe we should select a few key functions to use. @dami82, @SystemsBiologist, can you point me to a few of those? A short list of the most important cellmigRation functions would be quite helpful.

I think I can get it started. From the vignette, I see these functions are used (ignoring plot functions, which are not easy to unit-test):

- [x] OptimizeParams()
- [x] getOptimizedParams()
- [x] CellTracker()
- [x] getTracks()
- [x] ComputeTracksStats()
- [x] getCellsStats()
- [ ] VisualizeStackCentroids()
- [ ] visualizeCellTracks()
- [x] aggregateTrackedCells()
- [ ] CellMig()
- [x] DiRatio()
- [ ] MSD()
- [ ] getCellMigSlot()

Anything missing? Anything I should drop (either due to irrelevance or high computational demand)?

Edit: list above reformatted with checkboxes so I can keep track of what is implemented.

**Comment by SystemsBiologist** [comment]
I am superfine with the suggested functions!

**Comment by wleoncio** [comment]
Fixed by ea16c0ea21115f8a705fd3977fd177040db1db2c. Unmarked functions in the [post above](https://github.com/ocbe-uio/cellmigRation/issues/36#issuecomment-780462238) were not included because they are either plot functions or functions without examples.
