### ISSUE TITLE
Using vapply() and seq_*()

### ISSUE THREAD

**Issue by wleoncio** [SystemsBiologist/CellMigRation#37]
Source: https://github.com/Bioconductor/Contributions/issues/1618#issuecomment-696258765

- [x] REQUIRED: Avoid sapply(); use vapply() where possible.
- [x] REQUIRED: Avoid 1:...; use seq_len() or seq_along() where possible.

Please remember to add (#37) to the description of the commit fixing this issue.

**Comment by wleoncio** [comment]
Other connected PRs: #48, #49, #50, #51, #52, #53, #54, #55, #56. Mentioned here because the limit of linked PRs on the right panel has been reached.

**Comment by osorensen** [comment]
I have now remove all instances of `sapply()`, and also added `seq_len` and `seq_along` in the vicinity of `sapply`. In addition to the PRs mentioned above, there is a whole lot of merges directly to the `develop` branch. I have inspected the code and run it with the example data, where this exists, but there is of course a chance that I have introduced some bugs. When unit tests are in place for all functions (cf. #36 ), it will be easy to find any commits which might break the code.

**Comment by wleoncio** [comment]
Super work, @osorensen! I did find one leftover `sapply(1:` here:

https://github.com/ocbe-uio/cellmigRation/blob/32dfe93fe148d5d87fcad5321a8c154a3b2c72e1/R/all_functions.R#L611

**Comment by wleoncio** [comment]
For the record, there are currently still 363 instances of `1:x` left to be potentially replaced with `seq_len(x)` or `seq_along(x)`:

![image](https://user-images.githubusercontent.com/8234768/95072691-e00e4b80-070b-11eb-9775-16ef415d3a1c.png)

As a _general_ rule, `seq_len(x)` is the usual solution when `x` is an integer; if `x` is a vector, `seq_along(x)` is what you're probably looking for.

**Comment by osorensen** [comment]
@wleoncio , the leftover `sapply` you mentioned above is related to this PR #41 , and will be fixed once this one is merged. I think it is fine, so will merge it right away.

**Comment by wleoncio** [comment]
> @wleoncio , the leftover `sapply` you mentioned above is related to this PR #41 , and will be fixed once this one is merged. I think it is fine, so will merge it right away.

Oh, right, I forgot that one's still open! :grimacing:

**Comment by osorensen** [comment]
Regaring `seq_len`, Alvaro is aware that I don't have time for these, so I assume someone else will fix these.

**Comment by wleoncio** [comment]
This issue has been split into #59, #60 and #61.

**Comment by wleoncio** [comment]
Fixed on f38498fdda3554d5ef33613d1b5ee4970b94bdc2.
