### ISSUE TITLE
Long-running examples

### ISSUE THREAD

**Issue by osorensen** [SystemsBiologist/CellMigRation#6]
Here is a little note just to keep you informed:

When an R package is being tested (e.g., on CRAN or Bioconductor), all examples are run. The examples should therefore not take more than a few minutes, to avoid putting too much load on their servers. Since most of the examples in CellMigRation take very long, this would become an issue. I have fixed this by adding a “dontrun” argument around most examples, like this:

```r
#' \dontrun{
#' data(Trajectory_dataset)
#' df<-Trajectory_dataset
#' prepro<-PreProcessing(df,PixelSize=1.24, TimeInterval=10)
#' PerSp<-PerAndSpeed(prepro,TimeInterval=10,ExpName="ExpName")
#’ }
```

In the documentation, it looks like this:

```r
## Not run: 
data(Trajectory_dataset)
rmTD <- CellMig(Trajectory_dataset)
rmTD <- rmPreProcessing(rmTD)
rmTD <- DiRatio(rmTD, ExpName="Test")

## End(Not run)
## Not run: 
data(Trajectory_dataset)
df<-Trajectory_dataset
prepro<-PreProcessing(df,PixelSize=1.24, TimeInterval=10)
DR=DiRatio(prepro, ExpName="Test")

## End(Not run)
```

Using "dontrun" this much is not ideal, because since they are not run, the test process will not catch errors in the examples. @SystemsBiologist , would it be possible to add some much smaller examples that run faster? I think it is fine too keep the existing examples as is, but these would then be added.

**Comment by wleoncio** [comment]
I agree that keeping examples short and quick is always a good idea. The longer versions could be implemented as unit tests, which `R CMD check` still runs but has a much higher time tolerance. ;)

**Comment by osorensen** [comment]
@SystemsBiologist , One way to make the examples runnable is by subsetting, as I did in the README: `df <- Trajectory_dataset[1:100, ]`.

**Comment by dami82** [comment]
Why don’t you embed a toy dataset with only few cells and few stacks in the package data/? You can use dontrun, but it’s a double edged sword. As pointed out before, those lines are not evaluated.
Also, I think examples should be very simple, just to illustrate input/arguments and expected output. If you want something more fancy, consider writing a vignette.

Best regards,
Damiano

——
Damiano Fantini

**Comment by wleoncio** [comment]
Even though there doesn't seem to be a commit linking to this issue, I understand it has been addressed, since the package is currently passing `R CMD check` in a matter of seconds (at least on my i7 machine). Feel free to reopen this if it's not the case.
