### ISSUE TITLE
Invalid URLs in documentation

### ISSUE THREAD

**Issue by wleoncio** [SystemsBiologist/CellMigRation#71]
# Summary

The following files contain links to an invalid URL:

https://github.com/ocbe-uio/cellmigRation/blob/b751c9f1524e4102fb68eb560e0fe042d811de61/man/visualizeCellTracks.Rd#L46
https://github.com/ocbe-uio/cellmigRation/blob/b751c9f1524e4102fb68eb560e0fe042d811de61/man/visualizeTrcks.Rd#L50

Please advise on proper URLs to include (or commit changes directly to the [release-0.99.5](https://github.com/ocbe-uio/cellmigRation/tree/release-0.99.5) branch).

# Obtained output

![image](https://user-images.githubusercontent.com/8234768/109925254-cfb1cb00-7cc1-11eb-8267-6a0eed5cc9dc.png)

**Comment by wleoncio** [comment]
I've assigned this to @dami82 because that's the username that shows on `git blame` for the lines in question, but maybe @SystemsBiologist can also clarify the issue.

**Comment by dami82** [comment]
Hi Waldir, thanks for spotting this....
That was the old URL before we merged everything into cellmigRation.
I updated those 2 URLs both in the Rd files and the roxygen documentation.
